version: '1.0.{build}'

branches:  
 only:
  - core-net-1-0

install:
- cmd: dotnet restore -v warning


build_script:
- cmd: dotnet publish .\src\CoreDataStore.Web


test_script:
- ps: foreach ($d in dir .\test |? {$_.PSIsContainer -eq $True}){ &"dotnet" "test" $d.FullName }


artifacts:
  path: .\src\CoreDataStore.Web\bin\Debug\netcoreapp1.0\publish